// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mindash.Countdown.Web.Data;

#nullable disable

namespace Mindash.Countdown.Web.Migrations
{
    [DbContext(typeof(CountDownDBContext))]
    [Migration("20221016095126_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Mindash.Countdown.Web.Data.DTOS.DateModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Dates");
                });
#pragma warning restore 612, 618
        }
    }
}
